const errorMessage = {
    NO_CREDENTIALS: 'NO_CREDENTIALS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    FORBIDDEN: 'FORBIDDEN',
    BLOCKED_BY_CORS_POLICY: 'BLOCKED_BY_CORS_POLICY',
    DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}

export default errorMessage
