const errorMessage = {
    NO_CREDENTIALS: 'NO_CREDENTIALS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    FORBIDDEN: 'FORBIDDEN',
    BLOCKED_BY_CORS_POLICY: 'BLOCKED_BY_CORS_POLICY',
    DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    INCORRECT_USERNAME_OR_PASSWORD: 'INCORRECT_USERNAME_OR_PASSWORD',
    USERNAME_EXISTED: 'USERNAME_EXISTED',
    EMAIL_EXISTED: 'EMAIL_EXISTED',
    PHONE_NUMBER_EXISTED: 'PHONE_NUMBER_EXISTED',
    NO_PERMISSION: 'NO_PERMISSION',
    GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    UPLOAD_IMAGE_FAILED: 'UPLOAD_IMAGE_FAILED',
    DELETE_IMAGE_FAILED: 'DELETE_IMAGE_FAILED',
    EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED'
}

export default errorMessage
