const successMessage = {
    LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
    REGISTER_SUCCESSFULLY: 'REGISTER_SUCCESSFULLY',
    REFRESH_TOKEN_SUCCESSFULLY: 'REFRESH_TOKEN_SUCCESSFULLY'
}

export default successMessage
